baseURL = 'http://localhost'
languageCode = 'en-us'
title = 'Breizhcamp 2023 - Maven discovery'

theme = ["github.com/dzello/reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.highlight]
codeFences = false
